#~/.github/profiles.yml

web_app: # dbt project name - should match project name in first line of your dbt_project.yml
  target: prod # The target key, is the default target (profile) you connect with
  outputs: # a list of the targets (or profiles) you can connect to snowflake with
    dev: # the target name (profile name)
      account: "{{ env_var ('SNOWFLAKE_ACCOUNT')}}"
      database: "{{ env_var ('SNOWFLAKE_PROD_DATABASE')}}"
      password: "{{ env_var ('SVC_DBT_SNOWFLAKE_PASSWORD')}}"
      role: "{{ env_var ('SVC_DBT_SNOWFLAKE_ROLE')}}"
      schema: "{{ env_var ('SNOWFLAKE_PROD_SCHEMA')}}"
      threads: 4
      type: snowflake
      user: "{{ env_var ('SVC_DBT_SNOWFLAKE_USER')}}"
      warehouse: "{{ env_var ('SVC_DBT_SNOWFLAKE_WH')}}"
