name: build and deploy azure web app

on: workflow_dispatch

env:
  DBT_PROFILES_DIR: ./.github
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_PROD_DATABASE: ${{ secrets.SNOWFLAKE_PROD_DATABASE }}
  SVC_DBT_SNOWFLAKE_PASSWORD: ${{ secrets.SVC_DBT_SNOWFLAKE_PASSWORD }}
  SVC_DBT_SNOWFLAKE_ROLE: ${{ secrets.SVC_DBT_SNOWFLAKE_ROLE }}
  SNOWFLAKE_PROD_SCHEMA: ${{ secrets.SNOWFLAKE_PROD_SCHEMA }}
  SVC_DBT_SNOWFLAKE_USER: ${{ secrets.SVC_DBT_SNOWFLAKE_USER }}
  SVC_DBT_SNOWFLAKE_WH: ${{ secrets.SVC_DBT_SNOWFLAKE_WH }}

jobs:
  build:
    name: direct runner
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          dbt deps
          dbt build --full-refresh --target web_app

      - name: generate documentation
        run: dbt docs generate --target web_app

      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website
          path: /home/runner/work/wd_web_app/wd_web_app/target/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download website
        uses: actions/download-artifact@v3
        with:
          name: website
          path: ${{ github.workspace }}

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: ""
          api_location: "api" # Api source code path relative to repository root - optional
          skip_app_build: true
          ###### End of Repository/Build Configurations ######
